SELECT disease.map_id AS 'No.' ,disease.disease_name AS 'DISEASES (New Cases Only) ',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 1 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ) , 1, 0),0))) AS '1',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 2 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '2',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 3 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '3',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 4 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '4',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 5 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '5',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 6 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '6',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 7 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '7',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 8 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '8',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 9 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '9',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 10 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '10',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 11 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '11',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 12 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '12',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 13 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '13',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 14 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '14',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 15 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '15',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 16 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '16',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 17 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '17',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 18 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '18',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 19 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '19',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 20 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '20',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 21 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '21',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 22 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '22',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 23 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '23',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 24 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '24',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 25 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '25',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 26 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '26',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 27 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '27',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 28 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '28',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 29 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '29',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 30 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '30',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(disease.date_time)) = 31 AND (  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  ), 1, 0),0))) AS '31',
    IF(disease.value_coded IS NULL, 0, SUM(IF(DATE(disease.date_started) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(  DATE(disease.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(disease.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  , 1, 0),0))) AS 'TOTALS'


FROM
  (SELECT DISTINCT obs.obs_id AS obs_id,
                   obs.value_coded AS value_coded,
                   obs.voided AS voided,
                   obs.obs_datetime AS date_time,
                   patient.date_created AS first_visit_date,
                   disease_concepts_map.disease_name AS disease_name,
                   person.birthdate as birthdate,
                   visit.date_started AS date_started,
                   visit.date_stopped AS date_stopped,
                   disease_concepts_map.map_id AS map_id

FROM disease_concepts_map
 LEFT OUTER JOIN obs ON  obs.value_coded = disease_concepts_map.concept_id
 LEFT OUTER JOIN encounter ON encounter.encounter_id = obs.encounter_id
 LEFT OUTER JOIN visit ON visit.visit_id = encounter.visit_id
 LEFT OUTER JOIN patient ON patient.patient_id=obs.person_id
 LEFT OUTER JOIN person ON person.person_id=patient.patient_id
 ) AS disease
GROUP BY disease.map_id
UNION ALL

SELECT '62' AS 'NO.', ' '  AS 'DISEASES (New Cases Only) ',
    ' 'AS '1',
    ' ' AS '2',
    ' ' AS '3',
    ' ' AS '4',
    ' ' AS '5',
    ' ' AS '6',
    ' ' AS '7',
    ' ' AS '8',
    ' ' AS '9',
    ' ' AS '10',
    ' ' AS '11',
    ' ' AS '12',
    ' ' AS '13',
    ' ' AS '14',
    ' ' AS '15',
    ' ' AS '16',
    ' ' AS '17',
    ' ' AS '18',
    ' ' AS '19',
    ' ' AS '20',
    ' ' AS '21',
    ' ' AS '22',
    ' ' AS '23',
    ' ' AS '24',
    ' ' AS '25',
    ' ' AS '26',
    ' ' AS '27',
    ' ' AS '28',
    ' ' AS '29',
    ' ' AS '30',
    ' ' AS '31',
    ' ' AS 'TOTALS'

    UNION ALL

SELECT '63' AS 'NO.',' ALL OTHER DISEASES'  AS 'DISEASES (New Cases Only) ',
    '0'AS '1',
    '0' AS '2',
    '0' AS '3',
    '0' AS '4',
    '0' AS '5',
    '0' AS '6',
    '0' AS '7',
    '0' AS '8',
    '0' AS '9',
    '0' AS '10',
    '0' AS '11',
    '0' AS '12',
    '0' AS '13',
    '0' AS '14',
    '0' AS '15',
    '0' AS '16',
    '0' AS '17',
    '0' AS '18',
    '0' AS '19',
    '0' AS '20',
    '0' AS '21',
    '0' AS '22',
    '0' AS '23',
    '0' AS '24',
    '0' AS '25',
    '0' AS '26',
    '0' AS '27',
    '0' AS '28',
    '0' AS '29',
    '0' AS '30',
    '0' AS '31',
    '0' AS 'TOTALS'


    UNION ALL

SELECT '64' AS 'NO.',' NO. OF FIRST ATTENDANCES'  AS 'DISEASES (New Cases Only) ',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 1 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '1',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 2 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '2',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 3 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '3',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 4 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '4',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 5 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '5',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 6 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '6',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 7 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '7',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 8 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '8',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 9 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '9',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 10 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '10',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 11 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '11',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 12 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '12',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 13 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '13',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 14 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '14',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 15 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '15',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 16 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '16',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 17 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '17',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 18 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '18',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 19 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '19',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 20 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '20',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 21 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '21',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 22 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '22',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 23 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '23',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 24 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '24',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 25 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '25',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 26 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '26',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 27 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '27',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 28 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '28',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 29 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '29',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 30 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '30',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 31 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS '31',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF((  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) = DATE(client_visits.visit_date) , 1, 0),0))) AS 'TOTALS'

FROM
  (SELECT DISTINCT patient.patient_id AS patient_id,
                   visit.visit_type_id as visit_type,
                   visit.date_started AS visit_date,
                   person.birthdate as birthdate,
                   visit.date_stopped AS date_stopped,
                   patient.date_created AS first_visit_date,
                   person.gender AS patient_gender
   FROM visit
     INNER JOIN patient ON visit.patient_id = patient.patient_id AND DATE(visit.date_stopped) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE) AND patient.voided = 0 AND visit.voided = 0
     INNER JOIN person ON person.person_id = patient.patient_id AND person.voided = 0
   WHERE visit.voided=0 ) AS client_visits

        UNION ALL

SELECT '65' AS 'NO.',' RE-ATTENDANCES'  AS 'DISEASES (New Cases Only) ',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 1 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date), 1, 0),0))) AS '1',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 2 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '2',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 3 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '3',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 4 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '4',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 5 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '5',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 6 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '6',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 7 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '7',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 8 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '8',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 9 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '9',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 10 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '10',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 11 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '11',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 12 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '12',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 13 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '13',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 14 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '14',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 15 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '15',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 16 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '16',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 17 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '17',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 18 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '18',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 19 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '19',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 20 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '20',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 21 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '21',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 22 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '22',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 23 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '23',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 24 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '24',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 25 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '25',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 26 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '26',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 27 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '27',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 28 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '28',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 29 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '29',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 30 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '30',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF(DAY(DATE(client_visits.visit_date)) = 31 AND (  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS '31',
    IF(client_visits.patient_id IS NULL, 0, SUM(IF(DATE(client_visits.first_visit_date) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE),IF((  DATE(client_visits.date_stopped) BETWEEN (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 0 YEAR), INTERVAL 0 DAY)) AND (DATE_ADD(DATE_ADD(client_visits.birthdate, INTERVAL 5 YEAR), INTERVAL 0 DAY))  )  AND DATE(client_visits.first_visit_date) < DATE(client_visits.visit_date) , 1, 0),0))) AS 'TOTALS'
  FROM
  (SELECT DISTINCT patient.patient_id AS patient_id,
                   visit.visit_type_id as visit_type,
                   visit.date_started AS visit_date,
                   person.birthdate as birthdate,
                   visit.date_stopped AS date_stopped,
                   patient.date_created AS first_visit_date,
                   person.gender AS patient_gender
   FROM visit
     INNER JOIN patient ON visit.patient_id = patient.patient_id AND DATE(visit.date_stopped) BETWEEN CAST('#startDate#' AS DATE) AND CAST('#endDate#' AS DATE) AND patient.voided = 0 AND visit.voided = 0
     INNER JOIN person ON person.person_id = patient.patient_id AND person.voided = 0
   WHERE visit.voided=0 ) AS client_visits

    UNION ALL

    SELECT '66' AS 'NO.',' Referrals from other health facilities'  AS 'DISEASES (New Cases Only) ',
    '0'AS '1',
    '0' AS '2',
    '0' AS '3',
    '0' AS '4',
    '0' AS '5',
    '0' AS '6',
    '0' AS '7',
    '0' AS '8',
    '0' AS '9',
    '0' AS '10',
    '0' AS '11',
    '0' AS '12',
    '0' AS '13',
    '0' AS '14',
    '0' AS '15',
    '0' AS '16',
    '0' AS '17',
    '0' AS '18',
    '0' AS '19',
    '0' AS '20',
    '0' AS '21',
    '0' AS '22',
    '0' AS '23',
    '0' AS '24',
    '0' AS '25',
    '0' AS '26',
    '0' AS '27',
    '0' AS '28',
    '0' AS '29',
    '0' AS '30',
    '0' AS '31',
    '0' AS 'TOTALS'

    UNION ALL

    SELECT '67' AS 'NO.',' Referrals to other health facilities'  AS 'DISEASES (New Cases Only) ',
    '0'AS '1',
    '0' AS '2',
    '0' AS '3',
    '0' AS '4',
    '0' AS '5',
    '0' AS '6',
    '0' AS '7',
    '0' AS '8',
    '0' AS '9',
    '0' AS '10',
    '0' AS '11',
    '0' AS '12',
    '0' AS '13',
    '0' AS '14',
    '0' AS '15',
    '0' AS '16',
    '0' AS '17',
    '0' AS '18',
    '0' AS '19',
    '0' AS '20',
    '0' AS '21',
    '0' AS '22',
    '0' AS '23',
    '0' AS '24',
    '0' AS '25',
    '0' AS '26',
    '0' AS '27',
    '0' AS '28',
    '0' AS '29',
    '0' AS '30',
    '0' AS '31',
    '0' AS 'TOTALS'

    UNION ALL

    SELECT '68' AS 'NO.',' Referrals from Community unit'  AS 'DISEASES (New Cases Only) ',
    '0'AS '1',
    '0' AS '2',
    '0' AS '3',
    '0' AS '4',
    '0' AS '5',
    '0' AS '6',
    '0' AS '7',
    '0' AS '8',
    '0' AS '9',
    '0' AS '10',
    '0' AS '11',
    '0' AS '12',
    '0' AS '13',
    '0' AS '14',
    '0' AS '15',
    '0' AS '16',
    '0' AS '17',
    '0' AS '18',
    '0' AS '19',
    '0' AS '20',
    '0' AS '21',
    '0' AS '22',
    '0' AS '23',
    '0' AS '24',
    '0' AS '25',
    '0' AS '26',
    '0' AS '27',
    '0' AS '28',
    '0' AS '29',
    '0' AS '30',
    '0' AS '31',
    '0' AS 'TOTALS'

    UNION ALL

    SELECT '69' AS 'NO.',' Referals to Community UNit'  AS 'DISEASES (New Cases Only) ',
    '0'AS '1',
    '0' AS '2',
    '0' AS '3',
    '0' AS '4',
    '0' AS '5',
    '0' AS '6',
    '0' AS '7',
    '0' AS '8',
    '0' AS '9',
    '0' AS '10',
    '0' AS '11',
    '0' AS '12',
    '0' AS '13',
    '0' AS '14',
    '0' AS '15',
    '0' AS '16',
    '0' AS '17',
    '0' AS '18',
    '0' AS '19',
    '0' AS '20',
    '0' AS '21',
    '0' AS '22',
    '0' AS '23',
    '0' AS '24',
    '0' AS '25',
    '0' AS '26',
    '0' AS '27',
    '0' AS '28',
    '0' AS '29',
    '0' AS '30',
    '0' AS '31',
    '0' AS 'TOTALS'






